"""add_gmail_sync_fields

Revision ID: 1b19dc5b5a54
Revises: 3c1710ea9ea1
Create Date: 2026-03-18 10:57:58.242169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b19dc5b5a54'
down_revision: Union[str, None] = '3c1710ea9ea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gmail_refresh_token', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('gmail_connected', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('last_email_sync', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_email_sync')
    op.drop_column('users', 'gmail_connected')
    op.drop_column('users', 'gmail_refresh_token')
    # ### end Alembic commands ###
