"""add_user_plan_stripe

Revision ID: 3c1710ea9ea1
Revises: 62f8f38dad20
Create Date: 2026-03-18 10:38:42.015487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c1710ea9ea1'
down_revision: Union[str, None] = '62f8f38dad20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plan', sa.String(length=20), nullable=False, server_default='free'))
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stripe_customer_id')
    op.drop_column('users', 'plan')
    # ### end Alembic commands ###
